#!/usr/bin/env bash

directory="$HOME/.config/hypr/Wallpapers"
monitor=`hyprctl monitors | grep Monitor | awk '{print $2}'`

if [ -d "$directory" ]; then
    random_background=$(ls $directory/*.png | shuf -n 1)

    hyprctl hyprpaper unload all
    hyprctl hyprpaper preload $random_background
    hyprctl hyprpaper wallpaper "DP-2,$random_background"
    hyprctl hyprpaper wallpaper "DP-3,$random_background"

fi
